quarkus.http.port=8082

%prod.quarkus.mongodb.connection-string=mongodb://mongo:27017

quarkus.mongodb.database=rental

# Force Dev Services to use the modern Redpanda image
quarkus.kafka.devservices.image-name=docker.io/redpandadata/redpanda:v24.1.2